### ISSUE TITLE
How could I reproduce the results of QAT_DeiT on ImageNet?

### ISSUE THREAD

**Issue by KenRamzes** [megvii-research/Sparsebit#68]
I rewrite the related code in main.py  as follows:
```
    # set head and tail of model is 8bit
    model.model.patch_embed_proj.weight_quantizer.set_bit(bit=8)
    model.model.head.input_quantizer.set_bit(bit=8)
    model.model.head.weight_quantizer.set_bit(bit=8)
    # model.model.conv1.weight_quantizer.set_bit(bit=8)
    # model.model.fc.input_quantizer.set_bit(bit=8)
    # model.model.fc.weight_quantizer.set_bit(bit=8)
```
and training for 90 epoches, but I can`t get the same result that the readme provided.

**Comment by PeiqinSun** [comment]
1. the model is DeiT?
2. Is a pre-trained model used?
3. you should follow the hyper-parameters of [DeiT project](https://github.com/facebookresearch/deit/blob/main/main.py), our basecase is the hyper-parameters for CNN
4. The LSQ has a bug in GeLU which be fixed in https://github.com/megvii-research/Sparsebit/pull/65

**Comment by PeiqinSun** [comment]
The latest example of DeiT is updated. Please updates the master.
